apiVersion: v1
kind: Service
metadata:
  name: main-node-port
spec:
  type: NodePort
  ports:
    - port: 3050
      name: api
      targetPort: 8080
      nodePort: 31515
    - port: 3055
      name: client
      targetPort: 80
      nodePort: 31520
  selector:
    component: web
