apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-tracker-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: api
          image: rbertram8/error-tracker-api:v1.0
          ports:
            - containerPort: 8080
          env:
          - name: db_credentials
            value: bf4be85d529797:ca553c8e@
          - name: db_connection
            value: us-cdbr-east-02.cleardb.com/
          - name: db_parameters
            value: heroku_4d13ce5b7be4453?reconnect=truecharset=utf8&parseTime=True&loc=Local
        - name: client
          image: rbertram8/error-tracker-client:v1.0
          ports:
            - containerPort: 80
